### ISSUE TITLE
NPE in c.g.c.tomcat.logging.CloudFoundryFormatter.getLogger()

### ISSUE THREAD

**Issue by violetagg** [cloudfoundry/java-buildpack-support#7]
Hi,

In TomEE Buildpack we use Tomcat Logging Support 2.4.0_RELEASE.
From time to time I receive the exception below [1].

According to the source repository [2] this should not happen. Even the last commit is to prevent this NPE.

However if I browse the 2.4.0 RELEASE sources [3], I can see that the fix is not included even that it is committed in July. 

Do you plan to include it in the next release?

Thanks,
Violeta Georgieva

[1]
java.lang.NullPointerException
at com.gopivotal.cloudfoundry.tomcat.logging.CloudFoundryFormatter.getLogger(CloudFoundryFormatter.java:55)
at com.gopivotal.cloudfoundry.tomcat.logging.CloudFoundryFormatter.format(CloudFoundryFormatter.java:35)

[2] https://github.com/cloudfoundry/java-buildpack-support/blob/master/tomcat-logging-support/src/main/java/com/gopivotal/cloudfoundry/tomcat/logging/CloudFoundryFormatter.java
[3] https://github.com/cloudfoundry/java-buildpack-support/archive/v2.4.0.RELEASE.zip

**Comment by nebhale** [comment]
Published `v2.5.0.RELEASE`.

**Comment by violetagg** [comment]
Thanks
